<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:22:01 **/


$Definition['%s and you'] = '%s og dig';
$Definition['%s comment'] = '%s kommentar';
$Definition['%s comments'] = '%s kommentarer';
$Definition['%s Connect'] = '%s Connect';
$Definition['%s message'] = '%s besked';
$Definition['%s messages'] = '%s beskeder';
$Definition['%s New'] = '%s Ny';
$Definition['%s new'] = '%s ny';
$Definition['%s New Plural'] = '%s Nye';

$Definition['1 message'] = '1 besked';

$Definition['About'] = 'Omkring';
$Definition['Accepted'] = 'Accepteret';
$Definition['Activity'] = 'Aktivitet';
$Definition['Activity.AboutUpdate.FullHeadline'] = '%1$s opdaterede %6$s profil.';
$Definition['Activity.AboutUpdate.ProfileHeadline'] = '%1$s opdaterede %6$s profil.';
$Definition['Activity.ActivityComment.FullHeadline'] = '%1$s kommenterede på %4$s %8$s.';
$Definition['Activity.ActivityComment.ProfileHeadline'] = '%1$s';
$Definition['Activity.AddedToConversation.FullHeadline'] = '%1$s tilføjede dig til en %8$s.';
$Definition['Activity.AddedToConversation.ProfileHeadline'] = '%1$s tilføjede dig til en %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s kommenterede på din %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s kommenterede på din %8$s.';
$Definition['Activity.Comment'] = 'Kommentar';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s nævnte %3$s i en %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s nævnte %3$s i en %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s sendte dig en %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s sendte dig en %8$s.';
$Definition['Activity.DiscussionComment.FullHeadline'] = '%1$s kommenterede på %4$s %8$s.';
$Definition['Activity.DiscussionComment.ProfileHeadline'] = '%1$s kommenterede på %4$s %8$s.';
$Definition['Activity.DiscussionMention.FullHeadline'] = '%1$s nævnte %3$s i en %8$s.';
$Definition['Activity.DiscussionMention.ProfileHeadline'] = '%1$s nævnte %3$s i en %8$s.';
$Definition['Activity.Import.FullHeadline'] = '%1$s importeret data.';
$Definition['Activity.Import.ProfileHeadline'] = '%1$s importeret data.';
$Definition['Activity.Join.FullHeadline'] = '%1$s tilsluttede.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s tilsluttede.';
$Definition['Activity.JoinApproved.FullHeadline'] = '%1$s godkendte %4$s forespørgsel.';
$Definition['Activity.JoinApproved.ProfileHeadline'] = '%1$s godkendte %4$s forespørgsel.';
$Definition['Activity.JoinCreated.FullHeadline'] = '%3$s oprettede en bruger for %1$s.';
$Definition['Activity.JoinCreated.ProfileHeadline'] = '%3$s oprettede en bruger for %1$s.';
$Definition['Activity.JoinInvite.FullHeadline'] = '%1$s accepterede %4$s invitation til medlemsskab.';
$Definition['Activity.JoinInvite.ProfileHeadline'] = '%1$s accepterede %4$s invitation til medlemsskab.';
$Definition['Activity.NewDiscussion.FullHeadline'] = '%1$s startede en %8$s.';
$Definition['Activity.NewDiscussion.ProfileHeadline'] = '%1$s startede en %8$s.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s ændrede %6$s profil-billede.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s ændrede %6$s profil-billede.';
$Definition['Activity.RoleChange.FullHeadline'] = '%1$s ændrede %4$s rettigheder.';
$Definition['Activity.RoleChange.ProfileHeadline'] = '%1$s ændrede %4$s rettigheder.';
$Definition['Activity.SignIn.FullHeadline'] = '%1$s loggede på.';
$Definition['Activity.SignIn.ProfileHeadline'] = '%1$s loggede på.';
$Definition['Activity.WallComment.FullHeadline'] = '%1$s skrev på %4$s %5$s.';
$Definition['Activity.WallComment.ProfileHeadline'] = '%1$s skrev:';
$Definition['Add'] = 'Tilføj';
$Definition['Add Comment'] = 'Tilføj kommentar';
$Definition['Add Info &amp; Create Account'] = 'Tilføj information &amp; opret bruger';
$Definition['Add Message'] = 'Tilføj besked';
$Definition['Add People to this Conversation'] = 'Tilføj brugere til samtalen';
$Definition['All Conversations'] = 'Alle samtaler';
$Definition['All Discussions'] = 'Alle debatter';
$Definition['Allow other members to see your email?'] = 'Tillad at andre brugere kan se din email?';
$Definition['Announce'] = 'Udmeld';
$Definition['Applicants'] = 'Ansøgere';
$Definition['Apply'] = 'Påfør';
$Definition['Apply for Membership'] = 'Ansøg om medlemsskab';
$Definition['Are you sure you want to do that?'] = 'Er du sikker?';
$Definition['at'] = 'at';

$Definition['Back to Discussions'] = 'Tilbage til debatterne';
$Definition['Bookmark'] = 'Bogmærk';
$Definition['bookmarked discussion'] = 'bogmærket debat';
$Definition['Bookmarked Discussions'] = 'bogmærkede debatter';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'Ved at uploade en fil, bekræfter du at du har retten til at distrubere billedet og at det ikke krænker brugsbetingelserne';

$Definition['Cancel'] = 'Annuller';
$Definition['Categories'] = 'Kategorier';
$Definition['Category'] = 'Kategori';
$Definition['Change My Password'] = 'Skift mit kodeord';
$Definition['Change My Picture'] = 'Skift mit billede';
$Definition['Close'] = 'Luk';
$Definition['comment'] = 'kommenter';
$Definition['Comment'] = 'Kommenter';
$Definition['Confirm'] = 'Bekræft';
$Definition['Confirm Password'] = 'Bekræft kodeord';
$Definition['Connect'] = 'Forbind';
$Definition['conversation'] = 'samtale';
$Definition['Conversations'] = 'Samtaler';
$Definition['Create One.'] = 'Opret en';

$Definition['Dashboard'] = 'Admin';
$Definition['Date.DefaultDayFormat'] = '%G %e';
$Definition['Date.DefaultFormat'] = '%G %e, %Y';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Delete'] = 'Slet';
$Definition['Delete Account'] = 'Slet bruger';
$Definition['Delete Conversation'] = 'Slet samtale';
$Definition['Delete Discussion'] = 'Slet debat';
$Definition['discussion'] = 'debatter';
$Definition['Discussion Title'] = 'Debattens titel';
$Definition['Discussions'] = 'Debatter';
$Definition['Don\'t have an account? %s'] = 'Har du ikke en bruger? %s';
$Definition['dot'] = 'dot';
$Definition['Draft saved at %s'] = 'Udkast gemt ved %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Træk i firkanten nedenunder for at definere en mindre version af billedet';

$Definition['Edit'] = 'Rediger';
$Definition['Edit Account'] = 'Rediger konto';
$Definition['Edit My Account'] = 'Rediger min konto';
$Definition['Edit My Thumbnail'] = 'Rediger lille billede';
$Definition['Edit Preferences'] = 'Rediger indstillinger';
$Definition['Email'] = 'Email';
$Definition['Email Notifications'] = 'Email underrettelser';
$Definition['Email Unavailable'] = 'Email utilgængelig';
$Definition['EmailInvitation'] = 'Hej!

%1$s har inviteret dig til at deltage i %2$s. Hvis du vil deltage, kan du gøre det ved at klikke på dette link:

  %3$s

Hav en god dag!';
$Definition['EmailMembershipApproved'] = 'Hej %1$s,

Din ansøgning om medlemsskab er blevet godkendt. Log på nu ved at klikke på det følgende link:

  %2$s

Hav en god dag!';
$Definition['EmailNotification'] = '%1$s

Følg linket nedenunder for at se nærmere:
%2$s

Hav en god dag!';
$Definition['EmailPassword'] = 'Hej %1$s,

%2$s har nulstillet dit kodeord ved %3$s. Dine login oplysninger er nu

  Email: %6$s
  Kodeord: %5$s
  Adresse: %4$s

Hav en god dag!';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Følg linket for at se nærmere
%2$s

Hav en god dag!';
$Definition['EmailWelcome'] = 'Hej %1$s,

%2$s har oprettet en konto til dig ved %3$s. Dine login oplysninger er:

  Email: %6$s
  Kodeord: %5$s
  Adresse: %4$s

Hav en god dag!';
$Definition['EmailWelcomeConnect'] = 'Hej {User.Name},

Du er blevet forbundet til {Title}. Her er dine oplysninger:

  Brugernavn: {User.Name}
  Forbundet med: {ProviderName}

Du kan tilgå siden på {/,url,domain}.

Hav en god dag!';
$Definition['EmailWelcomeRegister'] = 'Hej {User.Name},

Du har oprettet en bruger ved {Title}. Her er dine oplysninger:

  Brugernavn: {User.Name}
  Email: {User.Email}

Du kan tilgå siden på {/,url,domain}.

Hav en god dag!';
$Definition['Enter the email address of the person you would like to invite:'] = 'Indtast email adressen på den person du vil invitere:';
$Definition['Enter your Email address'] = 'Indtast din email adresse';
$Definition['Enter your existing account password.'] = 'Indtast dit nuværende kodeord.';
$Definition['ErrorCredentials'] = 'Desværre, ingen bruger med den kombination af email og kode blev fundet.';
$Definition['ErrorPermission'] = 'Desværre, adgang nægtet.';
$Definition['ErrorRecordNotFound'] = 'Den forespurgte indtastning blev ikke fundet.';
$Definition['ErrorTermsOfService'] = 'Du skal godkende brugsbetingelserne.';

$Definition['Female'] = 'Kvinde';
$Definition['Forgot?'] = 'Glemt det?';

$Definition['Gender'] = 'Køn';
$Definition['GenderSuffix.First.f'] = '';
$Definition['GenderSuffix.First.m'] = '';
$Definition['GenderSuffix.Third.f'] = '';
$Definition['GenderSuffix.Third.m'] = '';
$Definition['Go'] = 'Ok';
$Definition['GuestModule.Message'] = 'Du er ny her. Hvis du vil involveres, klik på en af knapperne';

$Definition['he'] = 'han';
$Definition['her'] = 'hende';
$Definition['his'] = 'hans';
$Definition['Howdy, Stranger!'] = 'Halløj, fremmede!';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'Jeg accepterer <a id="TermsOfService" class="Popup" target="terms" href="%s">brugsbetingelserne</a>';
$Definition['I remember now!'] = 'Nu husker jeg det!';
$Definition['In this Conversation'] = 'I denne samtale';
$Definition['Inbox'] = 'Indbakke';
$Definition['Internal'] = 'Intern';
$Definition['Invitation Code'] = 'Invitations-kode';
$Definition['Invite'] = 'Inviter';
$Definition['Invited by'] = 'Inviteret af';

$Definition['Joined'] = 'Tilsluttet';

$Definition['Keep me signed in'] = 'Hold mig logget ind!';

$Definition['Last Active'] = 'Sidst aktiv';
$Definition['Login with Facebook'] = 'Log på med facebook';

$Definition['Male'] = 'Mand';
$Definition['Most recent by %1$s'] = 'Seneste af %1$s';
$Definition['My Bookmarks'] = 'Mine bogmærker';
$Definition['My Discussions'] = 'Mine debatter';
$Definition['My Drafts'] = 'Mine udkast';
$Definition['My Invitations'] = 'Mine invitationer';
$Definition['My Preferences'] = 'Mine indstillinger';

$Definition['Name Unavailable'] = 'Navn utilgængeligt';
$Definition['No discussions were found.'] = 'Ingen debat blev fundet';
$Definition['Notifications'] = 'Underrettelser';
$Definition['Notify me of private messages.'] = 'Underret mig om private beskeder.';
$Definition['Notify me when I am added to private conversations.'] = 'Underret mig når jeg bliver tilføjet private samtaler.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'Underret mig når brugere kommenterer på mine bogmærkede debatter.';
$Definition['Notify me when people comment on my discussions.'] = 'Underret mig når brugere kommenterer på mine debatter.';
$Definition['Notify me when people mention me in comments.'] = 'Underret mig når brugere nævner mig i kommentarer.';
$Definition['Notify me when people mention me in discussion titles.'] = 'Underret mig når brugere nævner mig i debatters titler.';
$Definition['Notify me when people reply to my wall comments.'] = 'Underret mig når brugere svarer på kommentarer på min væg.';
$Definition['Notify me when people write on my wall.'] = 'Underret mig når brugere skriver på min væg.';

$Definition['Okay'] = 'Okay';
$Definition['On'] = 'Til';
$Definition['Options'] = 'Indstillinger';
$Definition['Or you can...'] = 'Ellers kan du...';
$Definition['Original'] = 'Original';

$Definition['PageDetailsMessage'] = '%1$s til %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s til %2$s af %3$s';
$Definition['Password'] = 'Kodeord';
$Definition['PasswordRequest'] = 'Hej %1$s,

Nogen har forespurgt at nulstille dit kodeord ved %2$s. For at nulstille dit kodeord, følg dette link:

  %3$s

Hvis du ikke udførte denne forespørgsel, så se bort fra denne email.';
$Definition['Passwords don\'t match'] = 'Kodeordene er ikke de samme';
$Definition['Permalink'] = 'Permanent link';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Vent venligst mens du bliver viderestillet. Hvis du ikke viderestillet, klik <<a href="%s">her</a>.';
$Definition['Post Comment'] = 'Opret kommentar';
$Definition['Post Discussion'] = 'Opret debat';
$Definition['Powered by Vanilla'] = 'Powered by Vanilla';
$Definition['Preview'] = 'Se reslutat';
$Definition['Profile Picture'] = 'Profil-billede';

$Definition['Recent Activity'] = 'Nylig aktivitet';
$Definition['Recipients'] = 'Modtagere';
$Definition['Redirecting...'] = 'Omstiller...';
$Definition['Remember me on this computer'] = 'Husk mig på denne computer';
$Definition['Remove My Picture'] = 'Fjern mit billede';
$Definition['Request a new password'] = 'Efterspørg et nyt kodeord';
$Definition['Roles'] = 'Roller';

$Definition['Save'] = 'Gem';
$Definition['Save Draft'] = 'Gem udkast';
$Definition['Save Preferences'] = 'Gem præferencer';
$Definition['Search'] = 'Søg';
$Definition['Select an image on your computer (2mb max)'] = 'Vælg et billede på din computer (max 2mb)';
$Definition['Send %s a Message'] = 'Send %s en besked';
$Definition['Send Message'] = 'Send besked';
$Definition['Sent To'] = 'Sendt til';
$Definition['Share'] = 'Del';
$Definition['she'] = 'hun';
$Definition['Sign In'] = 'Log ind';
$Definition['Sign In with Google'] = 'Log på med Google';
$Definition['Sign In with OpenID'] = 'Log på med OpenID';
$Definition['Sign In with Twitter'] = 'Log på med Twitter';
$Definition['Sign Out'] = 'Log ud';
$Definition['Sign Up'] = 'Opret dig';
$Definition['Sink'] = 'Sink';
$Definition['somebody'] = 'nogen';
$Definition['Start a New Conversation'] = 'Start en ny samtale';
$Definition['Start a New Discussion'] = 'Start en ny debat';
$Definition['Start Conversation'] = 'Start en samtale';
$Definition['Started by %1$s'] = 'Startet af %1$s';
$Definition['Status'] = 'Status';

$Definition['Thank You!'] = 'Tak!';
$Definition['Thumbnail'] = 'Miniature billede';
$Definition['Transport error: %s'] = 'En fejl opstod mens din forespørgsel blev behandlet.<br />Serveren returnerede følgende fejl: %s';

$Definition['Unbookmark'] = 'Fjern bogmærke';
$Definition['Upload'] = 'Upload';
$Definition['Username'] = 'Brugernavn';

$Definition['ValidateBoolean'] = '%s er ikke en gyldig boolean.';
$Definition['ValidateConnection'] = 'Forbindelses-parametrene du angav oprettede ikke en forbindelse til databasen. Databasen rapporterede følgende fejl: <code>%s</code>';
$Definition['ValidateDate'] = '%s er ikke en gyldig dato.';
$Definition['ValidateDecimal'] = '%s er ikke et gyldigt decimaltal.';
$Definition['ValidateEmail'] = '%s er ikke en gyldig email.';
$Definition['ValidateEnum'] = '%s er ikke gyldig.';
$Definition['ValidateInteger'] = '%s er ikke et gyldigt heltal.';
$Definition['ValidateLength'] = '%1$s er %2$s karakterer for langt.';
$Definition['ValidateMatch'] = '%s felterne er ikke ens.';
$Definition['ValidateMinimumAge'] = 'Du skal være mindst 16 år gammel for at fortsætte.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Du skal vælge mindst et %s.';
$Definition['ValidateRegex'] = '%s ser ikke ud til at være i et korrekt format.';
$Definition['ValidateRequired'] = '%s er påkrævet.';
$Definition['ValidateRequiredArray'] = 'Du skal vælge mindst en %s.';
$Definition['ValidateTime'] = '%s er ikke et gyldigt tidspunkt.';
$Definition['ValidateTimestamp'] = '%s er ikek et gyldigt tids-stempel.';
$Definition['ValidateUsername'] = 'Brugernavne skal være mellem 3 og 20 karakterer langt og bestå af bogstaver, numre og underscore';
$Definition['ValidateVersion'] = '%s feltet er ikke et gyldigt versions-nummer. Se php version_compare() for eksempler på gyldigt versions-numre.';
$Definition['Visits'] = 'Besøgende';

$Definition['wall'] = 'væg';
$Definition['Why do you want to join?'] = 'Hvorfor vil du tilslutte dig?';
$Definition['Write a comment'] = 'Skriv en kommentar';
$Definition['Write Comment'] = 'Skriv kommentar';
$Definition['Write something about yourself...'] = 'Skriv noget om dig selv...';

$Definition['you'] = 'dig';
$Definition['You'] = 'Du';
$Definition['You already have an account here.'] = 'Du har allerede en konto her.';
$Definition['You are connected as %s through %s.'] = 'Du er forbundet som %s gennem %s.';
$Definition['You do not have any conversations.'] = 'Du har ingen samtaler.';
$Definition['You do not have any notifications yet.'] = 'Du har ingen underretninger endnu.';
$Definition['your'] = 'dine';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'Din forespørgsel vil blive gennemset af en administrator. Du vil blive underrettet på email når din forespørgsel bliver godkendt.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Dig registrerede brugernavn: <strong>%s</strong>';

// These additions taken from http://vanillaforums.org/discussion/14081/missing-definitions-in-the-baseline-locale

$Definition['Save Comment'] = 'Gem kommentar';
$Definition['Unannounce'] = 'Fjern udmelding';
$Definition['Announcement'] = 'Udmelding';
$Definition['Dismiss'] = 'Afvis';
$Definition['Closed'] = 'Lukket' ;
$Definition['Reopen'] = 'Genåbn';
$Definition['Old Password'] = 'Gammelt kodeord';
$Definition['New Password'] = 'Nyt kodeord';
$Definition['Change Password'] = 'Skift kodeord';
$Definition['Add a Comment'] = 'Tilføj en kommentar';
$Definition['Edit Discussion'] = 'Rediger debat';
$Definition['Uninvite'] = 'Fjern invitation';
$Definition['Send Again'] = 'Send igen';
$Definition['Pending'] = 'Afventer';

$Definition['Show All Categories'] = 'Vis alle kategorier';
$Definition['Mark All Viewed'] = 'Marker alt som set';
$Definition["Who's Online"] = "På lige nu";
$Definition['Attach a file'] = 'Vedhæft en fil';
$Definition['Create User'] = 'Opret bruger';
$Definition['Quote'] = 'Citér';
$Definition['Insert Image'] = 'Indsæt billede';
$Definition['message'] = 'besked';