<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:23:07 **/

$LocaleInfo['danish'] = array (
  'Locale' => 'da-DK',
  'Name' => 'Danish locale',
  'Description' => 'All of the text in a default Vanilla install.',
  'Version' => '1.0.1b',
  'Author' => 'Todd Burry',
  'AuthorEmail' => 'todd@vanillaforums.com',
  'AuthorUrl' => 'http://vanillaforums.org/profile/todd',
  'License' => 'GPL2',
);

